package com.website.mapper;

import com.website.entites.WebsiteRolePermission;
import com.website.entites.WebsiteRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsiteRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int countByExample(WebsiteRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int deleteByExample(WebsiteRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int insert(WebsiteRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int insertSelective(WebsiteRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    List<WebsiteRolePermission> selectByExample(WebsiteRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    WebsiteRolePermission selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") WebsiteRolePermission record, @Param("example") WebsiteRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExample(@Param("record") WebsiteRolePermission record, @Param("example") WebsiteRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByPrimaryKeySelective(WebsiteRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role_permission
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByPrimaryKey(WebsiteRolePermission record);
}