package com.website.mapper;

import com.website.entites.WebsiteUser;
import com.website.entites.WebsiteUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsiteUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int countByExample(WebsiteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int deleteByExample(WebsiteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int insert(WebsiteUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int insertSelective(WebsiteUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    List<WebsiteUser> selectByExample(WebsiteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    WebsiteUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") WebsiteUser record, @Param("example") WebsiteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExample(@Param("record") WebsiteUser record, @Param("example") WebsiteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByPrimaryKeySelective(WebsiteUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByPrimaryKey(WebsiteUser record);
}