package com.website.mapper;

import com.website.entites.WebsiteUserRoleExample;
import com.website.entites.WebsiteUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsiteUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int countByExample(WebsiteUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int deleteByExample(WebsiteUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int deleteByPrimaryKey(WebsiteUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int insert(WebsiteUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int insertSelective(WebsiteUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    List<WebsiteUserRoleKey> selectByExample(WebsiteUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") WebsiteUserRoleKey record, @Param("example") WebsiteUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_user_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExample(@Param("record") WebsiteUserRoleKey record, @Param("example") WebsiteUserRoleExample example);
}