package com.website.mapper;

import com.website.entites.WebsiteProject;
import com.website.entites.WebsiteProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsiteProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int countByExample(WebsiteProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int deleteByExample(WebsiteProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int deleteByPrimaryKey(Long projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int insert(WebsiteProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int insertSelective(WebsiteProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    List<WebsiteProject> selectByExampleWithBLOBs(WebsiteProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    List<WebsiteProject> selectByExample(WebsiteProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    WebsiteProject selectByPrimaryKey(Long projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") WebsiteProject record, @Param("example") WebsiteProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") WebsiteProject record, @Param("example") WebsiteProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExample(@Param("record") WebsiteProject record, @Param("example") WebsiteProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByPrimaryKeySelective(WebsiteProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WebsiteProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByPrimaryKey(WebsiteProject record);
}