package com.website.mapper;

import com.website.entites.WebsiteRole;
import com.website.entites.WebsiteRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsiteRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int countByExample(WebsiteRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int deleteByExample(WebsiteRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int insert(WebsiteRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int insertSelective(WebsiteRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    List<WebsiteRole> selectByExample(WebsiteRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    WebsiteRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") WebsiteRole record, @Param("example") WebsiteRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByExample(@Param("record") WebsiteRole record, @Param("example") WebsiteRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByPrimaryKeySelective(WebsiteRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_role
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    int updateByPrimaryKey(WebsiteRole record);
}