package com.website.entites;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class WebsiteProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public WebsiteProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Long value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Long value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Long value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Long value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Long value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Long> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Long> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Long value1, Long value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Long value1, Long value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectUrlIsNull() {
            addCriterion("project_url is null");
            return (Criteria) this;
        }

        public Criteria andProjectUrlIsNotNull() {
            addCriterion("project_url is not null");
            return (Criteria) this;
        }

        public Criteria andProjectUrlEqualTo(String value) {
            addCriterion("project_url =", value, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlNotEqualTo(String value) {
            addCriterion("project_url <>", value, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlGreaterThan(String value) {
            addCriterion("project_url >", value, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlGreaterThanOrEqualTo(String value) {
            addCriterion("project_url >=", value, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlLessThan(String value) {
            addCriterion("project_url <", value, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlLessThanOrEqualTo(String value) {
            addCriterion("project_url <=", value, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlLike(String value) {
            addCriterion("project_url like", value, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlNotLike(String value) {
            addCriterion("project_url not like", value, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlIn(List<String> values) {
            addCriterion("project_url in", values, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlNotIn(List<String> values) {
            addCriterion("project_url not in", values, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlBetween(String value1, String value2) {
            addCriterion("project_url between", value1, value2, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectUrlNotBetween(String value1, String value2) {
            addCriterion("project_url not between", value1, value2, "projectUrl");
            return (Criteria) this;
        }

        public Criteria andProjectTopicIsNull() {
            addCriterion("project_topic is null");
            return (Criteria) this;
        }

        public Criteria andProjectTopicIsNotNull() {
            addCriterion("project_topic is not null");
            return (Criteria) this;
        }

        public Criteria andProjectTopicEqualTo(String value) {
            addCriterion("project_topic =", value, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicNotEqualTo(String value) {
            addCriterion("project_topic <>", value, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicGreaterThan(String value) {
            addCriterion("project_topic >", value, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicGreaterThanOrEqualTo(String value) {
            addCriterion("project_topic >=", value, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicLessThan(String value) {
            addCriterion("project_topic <", value, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicLessThanOrEqualTo(String value) {
            addCriterion("project_topic <=", value, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicLike(String value) {
            addCriterion("project_topic like", value, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicNotLike(String value) {
            addCriterion("project_topic not like", value, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicIn(List<String> values) {
            addCriterion("project_topic in", values, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicNotIn(List<String> values) {
            addCriterion("project_topic not in", values, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicBetween(String value1, String value2) {
            addCriterion("project_topic between", value1, value2, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTopicNotBetween(String value1, String value2) {
            addCriterion("project_topic not between", value1, value2, "projectTopic");
            return (Criteria) this;
        }

        public Criteria andProjectTextIsNull() {
            addCriterion("project_text is null");
            return (Criteria) this;
        }

        public Criteria andProjectTextIsNotNull() {
            addCriterion("project_text is not null");
            return (Criteria) this;
        }

        public Criteria andProjectTextEqualTo(String value) {
            addCriterion("project_text =", value, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextNotEqualTo(String value) {
            addCriterion("project_text <>", value, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextGreaterThan(String value) {
            addCriterion("project_text >", value, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextGreaterThanOrEqualTo(String value) {
            addCriterion("project_text >=", value, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextLessThan(String value) {
            addCriterion("project_text <", value, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextLessThanOrEqualTo(String value) {
            addCriterion("project_text <=", value, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextLike(String value) {
            addCriterion("project_text like", value, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextNotLike(String value) {
            addCriterion("project_text not like", value, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextIn(List<String> values) {
            addCriterion("project_text in", values, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextNotIn(List<String> values) {
            addCriterion("project_text not in", values, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextBetween(String value1, String value2) {
            addCriterion("project_text between", value1, value2, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectTextNotBetween(String value1, String value2) {
            addCriterion("project_text not between", value1, value2, "projectText");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateIsNull() {
            addCriterion("project_create_date is null");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateIsNotNull() {
            addCriterion("project_create_date is not null");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("project_create_date =", value, "projectCreateDate");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("project_create_date <>", value, "projectCreateDate");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("project_create_date >", value, "projectCreateDate");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("project_create_date >=", value, "projectCreateDate");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("project_create_date <", value, "projectCreateDate");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("project_create_date <=", value, "projectCreateDate");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("project_create_date in", values, "projectCreateDate");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("project_create_date not in", values, "projectCreateDate");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("project_create_date between", value1, value2, "projectCreateDate");
            return (Criteria) this;
        }

        public Criteria andProjectCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("project_create_date not between", value1, value2, "projectCreateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table website_project
     *
     * @mbggenerated do_not_delete_during_merge Mon Feb 20 19:45:54 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table website_project
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}