package com.website.entites;

import java.util.Date;

public class WebsiteUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.user_id
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.login_account
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private String loginAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.login_passwd
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private String loginPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.user_name
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.user_head
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private String userHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.user_phone
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.user_email
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.user_sex
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.user_birthday
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.register_date
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.user_phone_verify
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private Boolean userPhoneVerify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_user.user_email_verify
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    private Boolean userEmailVerify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.user_id
     *
     * @return the value of website_user.user_id
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.user_id
     *
     * @param userId the value for website_user.user_id
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.login_account
     *
     * @return the value of website_user.login_account
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.login_account
     *
     * @param loginAccount the value for website_user.login_account
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.login_passwd
     *
     * @return the value of website_user.login_passwd
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public String getLoginPasswd() {
        return loginPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.login_passwd
     *
     * @param loginPasswd the value for website_user.login_passwd
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setLoginPasswd(String loginPasswd) {
        this.loginPasswd = loginPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.user_name
     *
     * @return the value of website_user.user_name
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.user_name
     *
     * @param userName the value for website_user.user_name
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.user_head
     *
     * @return the value of website_user.user_head
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public String getUserHead() {
        return userHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.user_head
     *
     * @param userHead the value for website_user.user_head
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setUserHead(String userHead) {
        this.userHead = userHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.user_phone
     *
     * @return the value of website_user.user_phone
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.user_phone
     *
     * @param userPhone the value for website_user.user_phone
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.user_email
     *
     * @return the value of website_user.user_email
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.user_email
     *
     * @param userEmail the value for website_user.user_email
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.user_sex
     *
     * @return the value of website_user.user_sex
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.user_sex
     *
     * @param userSex the value for website_user.user_sex
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.user_birthday
     *
     * @return the value of website_user.user_birthday
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.user_birthday
     *
     * @param userBirthday the value for website_user.user_birthday
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.register_date
     *
     * @return the value of website_user.register_date
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.register_date
     *
     * @param registerDate the value for website_user.register_date
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.user_phone_verify
     *
     * @return the value of website_user.user_phone_verify
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public Boolean getUserPhoneVerify() {
        return userPhoneVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.user_phone_verify
     *
     * @param userPhoneVerify the value for website_user.user_phone_verify
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setUserPhoneVerify(Boolean userPhoneVerify) {
        this.userPhoneVerify = userPhoneVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_user.user_email_verify
     *
     * @return the value of website_user.user_email_verify
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public Boolean getUserEmailVerify() {
        return userEmailVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_user.user_email_verify
     *
     * @param userEmailVerify the value for website_user.user_email_verify
     *
     * @mbggenerated Mon Feb 20 19:45:54 CST 2017
     */
    public void setUserEmailVerify(Boolean userEmailVerify) {
        this.userEmailVerify = userEmailVerify;
    }
}